// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZEG5BqmeSJEoKfe0Jbl5xWtA9YX4Oxk',
    appId: '1:294427493136:web:d852b90fc8f8af58081b95',
    messagingSenderId: '294427493136',
    projectId: 'klgcc-13f7d',
    authDomain: 'klgcc-13f7d.firebaseapp.com',
    storageBucket: 'klgcc-13f7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUGJgSrAMuOQZMcNOsKu9pPRvBbzFlwYw',
    appId: '1:294427493136:android:77c9008eeb5b5314081b95',
    messagingSenderId: '294427493136',
    projectId: 'klgcc-13f7d',
    storageBucket: 'klgcc-13f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2etfBLN6VUNaZIEICja9XLDg9TUuu4e0',
    appId: '1:294427493136:ios:5eefaaf30df9037c081b95',
    messagingSenderId: '294427493136',
    projectId: 'klgcc-13f7d',
    storageBucket: 'klgcc-13f7d.appspot.com',
    iosClientId: '294427493136-2atl0mq568oivddirnceeqhj93vaul1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.zegocloudTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2etfBLN6VUNaZIEICja9XLDg9TUuu4e0',
    appId: '1:294427493136:ios:5eefaaf30df9037c081b95',
    messagingSenderId: '294427493136',
    projectId: 'klgcc-13f7d',
    storageBucket: 'klgcc-13f7d.appspot.com',
    iosClientId: '294427493136-2atl0mq568oivddirnceeqhj93vaul1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.zegocloudTest2',
  );
}
